# Sample Google Cloud Build configuration for VideoSearcher frontend
steps:
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        npm run build
artifacts:
  objects:
    location: 'gs://YOUR_BUCKET_NAME/video-searcher-frontend/'
    paths: ['dist/**']
# Replace YOUR_BUCKET_NAME with your actual GCS bucket.
