steps:
  # -------------------------------
  # 1) Build FRONTEND Docker image
  # -------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-searcher-frontend'
      - '--build-arg'
      - 'VITE_API_URL=https://video-searcher-backend-z7yz7rqneq-uc.a.run.app'
      - './frontend'

  # -------------------------------
  # 2) Push FRONTEND Docker image
  # -------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/video-searcher-frontend']

  # -------------------------------
  # 3) Deploy FRONTEND to Cloud Run
  # -------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'video-searcher-frontend',
        '--image=gcr.io/$PROJECT_ID/video-searcher-frontend',
        '--region=us-central1',
        '--platform=managed',
        '--allow-unauthenticated',
        '--port=8080',
      ]

  # -------------------------------
  # 4) Build BACKEND with Node 20
  # -------------------------------
  - name: 'node:20'
    dir: 'backend'
    entrypoint: npm
    args: ['ci']

  - name: 'node:20'
    dir: 'backend'
    entrypoint: npm
    args: ['run', 'build']

  # -------------------------------
  # 5) Deploy BACKEND to Cloud Run
  # -------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'video-searcher-backend',
        '--source=backend/',
        '--region=us-central1',
        '--allow-unauthenticated',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
